import java.util.Arrays;
import java.util.ArrayList;
import java.util.HashMap;

public class TracksAndLyrics {
    public static void main(String[] args) {

    HashMap<String, String> trackList = new HashMap<String, String>();
trackList.put("Map of the Problematique", "Fear and panic in the air I want to be free From desolation and despair And I feel like everything I sow Is being swept away Well I refuse to let you go I can't get it right Get it right Since I met you Loneliness be over When will this loneliness be over? Life will flash before my eyes So scattered and lost I want to touch the other side And no one thinks they are to blame Why can't we see That when we bleed we bleed the same? I can't get it right Get it right Since I met you Loneliness be over When will this loneliness be over? Loneliness be over When will this loneliness be over?");
    trackList.put("Intro", "Sieg heil - Marsch!");
    trackList.put("Apocalypse Please", "[Verse 1] Declare this an emergency Come on and spread a sense of urgency And pull us through And pull us through [Chorus] And this is the end, the end This is the end Of the world [Verse 2] And it's time we saw a miracle Come on, it's time for something biblical To pull us through And pull us through [Chorus] And this is the end, the end This is the end Of the world [Verse 3] Proclaim eternal victory Come on and change the course of history And pull us through And pull us through [Chorus] And this is the end, the end This is the end Of the world");
    trackList.put("Time is Running Out", "[Verse 1] I think I'm drowning Asphyxiating I wanna break this spell That you've created You're something beautiful A contradiction I wanna play the game I want the friction You will be the death of me Yeah, you will be the death of me [Pre-Chorus] Bury it I won't let you bury it I won't let you smother it I won't let you murder it [Chorus] Our time is running out Our time is running out You can't push it underground You can't stop it screaming out [Verse 2] I wanted freedom Bound and restricted I tried to give you up But I'm addicted Now that you know I'm trapped Sense of elation You'd never dream of Breaking this fixation You will squeeze the life out of me [Pre-Chorus] Bury it I won't let you bury it I won't let you smother it I won't let you murder it [Chorus] Our time is running out Our time is running out You can't push it underground You can't stop it screaming out [Bridge] How did it come to this? Ooohhhh, yeah-yeah-yeah-yeah Ooohhhh, yeah-yeah-yeah-yeah-yeah Ooohhhh, Yeah-yeah, yeah-yeah-yeah! Yeah, you will suck the life out of me [Pre-Chorus] Bury it I won't let you bury it I won't let you smother it I won't let you murder it [Chorus] Our time is running out Our time is running out You can't push it underground You can't stop it screaming out [Bridge] How did it come to this? Ooohhhh, yeah-yeah-yeah-yeah Ooohhhh, yeah-yeah-yeah-yeah-yeah Ooohhhh, Yeah-yeah, yeah-yeah-yeah!");
    trackList.put("Sing for Absolution", "[Verse 1] Lips are turning blue A kiss that can't renew I only dream of you My beautiful Tiptoe to your room A starlight in the gloom I only dream of you And you never knew [Hook] Sing for absolution I will be singing And falling from your grace [Verse 2] There's nowhere left to hide In no one to confide The truth burns deep inside And will never die Lips are turning blue A kiss that can't renew I only dream of you My beautiful [Hook] Sing for absolution I will be singing And falling from your grace [Guitar Break] [Hook] Sing for absolution I will be singing And falling from your grace [Outro] Our wrongs remain unrectified And our souls won't be exhumed");
    trackList.put("Stockholm Syndrome", "[Verse 1] I won't stand in your way Let your hatred grow And she'll scream and she'll shout and she'll pray And she had a name, yeah she had a name [Verse 2] I won't hold you back Let your anger rise And we'll fly and we'll fall and we'll burn No one will recall, no one will recall [Chorus] This is the last time I'll abandon you And this is the last time I'll forget you I wish I could [Verse 3] Look to the stars Let hope burn in your eyes And we'll love and we'll hate and we'll die All to no avail, all to no avail [Chorus] This is the last time I'll abandon you And this is the last time I'll forget you I wish I could [Instrumental Break] [Chorus] This is the last time I'll abandon you And this is the last time I'll forget you I wish I could I wish I could");
    System.out.println("THE TRACK REQUESTED IS HERE IN CAPS SO IT'S NOT LOST!!--->>>> :" + trackList.get("Map of the Problematique")  + "                        ");
    for (HashMap.Entry<String, String> listTrackList : trackList.entrySet()) {
        System.out.println("Track : " + listTrackList.getKey() + ", Lyrics: " + listTrackList.getValue());
    }
    }
}